### ISSUE TITLE
“Unable to read disc” error on 3.10U , etc

### ISSUE THREAD

**Issue by amalgamat3** [CTurt/FreeDVDBoot#10]
Hi, I’ve tried several times to get FDVDB to work but have only had one successful attempt (and accidentally ruined that disc afterward, oops.)

I originally used the first version of the 3.10EU iso which worked once, but I have been unable to get the new “all regions” version working. Both DVD’s I burned are DVD+R, & were verified. A normal DVD movie starts and plays fine though.

Console: SCPH-70012 / slim
DVD Player: 3.10U

I burned the original disc through Win10 & the second version was done through ImgBurn, if that makes a difference.

I am not sure what to do going forward or what I may be doing wrong. I’ve searched around for other advice/troubleshooting before asking anywhere (also my first time using github for this stuff, sorry, I’m a newbie to tech talk)

I feel like it might could be a physical error but I’m not sure if it’s the new iso or my PS2

**Comment by YourKalamity** [comment]
Did you make sure to finalise the disc after burning?

**Comment by amalgamat3** [comment]
ImgBurn says the disc was finalized, they're only R discs and not RW
I'm not sure what else it could be, hm
I have also tried weighing the lid closed in case that was an issue but it didn't seem to make a difference

**Comment by ChrisFigura** [comment]
I had the same issue, I tried burning the hybrid and the 3.10 all region images several times and I couldn’t get them to boot on my PS2.

If I go to https://github.com/CTurt/FreeDVDBoot/commit/7192bb24695b51134bcd3fd054ae27d75993380c and burn the 3.10EU image from there, it works just fine though.

Console: SCPH-70012 / slim
DVD Player: 3.10U

**Comment by CTurt** [comment]
Hi.

Sorry for the confusion but those two files are identical (3.10E and 3.10 all regions), I just renamed it when it was confirmed working on other regions - you can see here if you don't believe me:

https://github.com/CTurt/FreeDVDBoot/commit/5e2aed3ca37757b2461ffe702e410658b643d39b#diff-488c28cc5f74e6dc3eb3a0cbfe447014

It sounds like in these cases, it is a problem with your burning setup not being consistent (as same file is working on one burn, but not on other burns).

Regarding hybrid not working on 3.10, I will test it myself to confirm today. Pretty confident about it though.
