### ISSUE TITLE
Storage devices don’t show up on boot till I UNPLUG my controller

### ISSUE THREAD

**Issue by dmonskull** [CTurt/FreeDVDBoot#103]
Whenever I boot with the disc no Storage devices show up, that’s till I unplug my controller then they show up right away and then I can plug my controller back in and everything works properly. Not sure what causes this but I thought I’d put it out there Incase anyone else is having problems loading in. 

I first found out how to make it pop up because my controller never works off start I’ll always have to unplug and plug it back to get it to work and after doing this I noticed it made Ulaunch start working. So if anyone else is having problems try this!!!

**Comment by CTurt** [comment]
Thank you, I can add a note about this to the README.
