### ISSUE TITLE
BIOS Dumper V2 - Possible with this setup?

### ISSUE THREAD

**Issue by derickRenwick** [CTurt/FreeDVDBoot#105]
Hey I am wondering about if it is possible to do a BIOS dump using BIOS Dumper V2 and the FreeDVDBoot method.

I imagine that using the iso on a disk would not work as the FreeDVDBoot disk needs to be in the drive (AFAIK).

The usb method with a binary I think would work but I wonder if it would need to overwrite the files or have a directory set within a config on the usb drive running ELF.

I think I could boot the console with the Binary on the usb, transfer the binary to the appropriate on console directory. 

Reboot with a cleared/empty usb for the BIOS dump.

My only concern is if fully powering off, to give me time to switch the usb, may cause an issue as the instructions generally show a quick reset (one press).

Once again not really sure if its possible but it seems it should be, any insight appreciated.

**Comment by CTurt** [comment]
Not 100% sure I understand the requirement of this tool and the question. Once FreeDVDBoot has booted into uLanchELF the disc is no longer needed and can be removed/swapped. You can run any homebrew you like from USB mass storage.

**Comment by derickRenwick** [comment]
Hey CTurt, thanks for the reply. I was being overly cautious, I was able to use the BIOS dumper with no issues.

If anyone else is new and looking to accomplish the same I used the usb to cut and paste the binaries (BIOS Dumper 2) to a memory card. Restarted and loaded the binary from the memory card to run the binaries.

Thanks for the excellent work.
