### ISSUE TITLE
Installation impossible

### ISSUE THREAD

**Issue by link0308** [CTurt/FreeDVDBoot#118]
Hello, here is my problem, I am in scph 9004, cd player 2.00, playstation driver 2.00, DVD player 3.11E. I downloaded the freedvdboot as well as the Hybrid 3.11 iso. I burned the iso file. and slipped the freedvdboot folder into the USB stick in fat32. I plugged the key into the console and put the burn DVD in the console. previously I put my console in English because my console is in French mode. I turned on my console, the screen went freedvdboot then I went to mass, file FMCBInstaller. Elf. when i launched the file i had to install it at the interface: "warning this console does not support fmcb, however, you can still make installation with it". I specify that my console is not then, nor anything else. can someone help me please. Thank you

**Comment by CTurt** [comment]
I don't maintain FreeMCBoot project so can't help with that - but I do know it's not compatible with all consoles, but FreeDVDBoot worked for you, so you can just use that :)
