### ISSUE TITLE
DVD 3.11U Black Screen Freeze

### ISSUE THREAD

**Issue by Undefinedghost** [CTurt/FreeDVDBoot#121]
Screen will flash in corners of the screen for a fraction of a second then be left with a black screen. I've attempted the following: No USB plugged in, No Memory Cards, No Controller, Burned using different discs, Burned using different programs, Booting image on boot and from the browser, and waiting 10+ minutes. I'm using Verbatim DVD-R discs (printable and non-printable)

PS2 plays games and DVDs so I'm unsure where to go from here. Any help would be appreciated.

PS2 SCPH-90001
Browser: 1.40
CD Player: 2.00
PS Driver: 2.00
DVD Player: 3.11U

**Comment by TnA-Plastic** [comment]
Are you - by chance - using a Laptop-Writer?

**Comment by Undefinedghost** [comment]
No, I'm using model LG UH12NS30 blu-ray/dvd/cd burner

**Comment by Nuespeed** [comment]
Hello I found a solution to this personally and I’m going to pass it to you. I discovered that the download saying it works for all ps2’s gave me a black screen whenever I tried loading the disc. So I found a download on psx place that gave the 3.11 only and that one managed to work for me. I used cdburnerxp on x1 speed but didnt check mark dvd compat or mode 2x. I have a ps2 900001 with 3.11 u drive and this worked for me

**Comment by Nuespeed** [comment]
https://www.psx-place.com/threads/freedvdboot.30220/

**Comment by Undefinedghost** [comment]
I'll give it a try and come back with the results

**Comment by Undefinedghost** [comment]
PERFECT! This worked beautifully, thank you

**Comment by SamuraisDoJo** [comment]
> https://www.psx-place.com/threads/freedvdboot.30220/

DUDE YOU SAVED ME....... Ive burned so many disc different ways with the iso that was provided for ALL SLIMS and it doesnt work for some reason. 

Downloaded the 3.11 only iso and burned the way you did and worked first try....... THANK YOU FOR THAT LINK

**Comment by CTurt** [comment]
There was a regression, updated the ISO. Sorry about that! Glad you were able to get a working one elsewhere.
