### ISSUE TITLE
DVD 3.11E Black Screen Freeze

### ISSUE THREAD

**Issue by kkristof999** [CTurt/FreeDVDBoot#122]
When I insert the DVD (DVD-R burned with IMGBurn Desktop), it spins up, and my system recognises it as DVD-VIDEO, after selecting it, the screen goes black, and some white squeres flashes on the screen for around a second, but after that I can only see a black screen. From now on the console freezes and nothing happens until I reset it. During the black screen the disc continue to spin, and the laser is still reading the disc. (the console is taken apart because of the back lid sensor). It makes no difference, what is connected. The console can play DVD-Movies without a problem (both burned and factory DVDs).

Version Information:
Console                    SCPH-75004
Browser                    1.40
CD Player                 2.00
PlayStation Driver    2.00
DVD Player              3.11E

**Comment by Nuespeed** [comment]
Hello I found a solution to this personally and I’m going to pass it to you. I discovered that the download saying it works for all ps2’s gave me a black screen whenever I tried loading the disc. So I found a download on psx place that gave the 3.11 only and that one managed to work for me. I used cdburnerxp on x1 speed but didnt check mark dvd compat or mode 2x. I have a ps2 900001 with 3.11 u drive and this worked for me

**Comment by kkristof999** [comment]
It worked flawlessly, like you said.
I found the ISOs here: https://www.psx-place.com/threads/freedvdboot.30220/
I downloaded the: 3.11 only - all regions - English lang.iso
Here are my burning settings:
![Burn settings](https://user-images.githubusercontent.com/68541202/88097596-add36000-cb98-11ea-9951-e21e16e921df.png)
