### ISSUE TITLE
Black screen on 3.11E SCPH-90004 8C

### ISSUE THREAD

**Issue by Fran7Ribeiro** [CTurt/FreeDVDBoot#124]
Hi, the disk I use is a DVD-R burned with ImgBurn at 4X. I used the latest ISO for every versions. The laser is working fine, I have set language to English and RGB output.
I tried removing memory card and controller, but nothing worked.
I will leave a video so you know what happens.

[WhatsApp Video 2020-07-20 at 17.33.45.mp4.zip](https://github.com/CTurt/FreeDVDBoot/files/4948934/WhatsApp.Video.2020-07-20.at.17.33.45.mp4.zip)

**Comment by pr47h5** [comment]
I'm having that too

**Comment by yoosf9760** [comment]
The same problem I have

**Comment by Fran7Ribeiro** [comment]
Just solved it, it's now working! 
Try burning with different software. Apparently for this user ImgBurn didn't work, but CDBurnerXP with 1x speed, compatibility settings, and finalize option worked.

**Comment by pr47h5** [comment]
@Fran7Ribeiro can you send me screenshot of your settings? i tried but it did work. if you give a screenshot I'll see if I've made any mistake

**Comment by Fran7Ribeiro** [comment]
> @Fran7Ribeiro can you send me screenshot of your settings? i tried but it did work. if you give a screenshot I'll see if I've made any mistake

I also switched the ISO to the hybrid one, but I think it's not that problem. Do you want the burner or PS2 settings?

**Comment by yoosf9760** [comment]
Can you send a picture of the program that you use in the burning process

**Comment by yoosf9760** [comment]
Can you send updated links 3.11

**Comment by Fran7Ribeiro** [comment]
I used this ISO, https://www.ps2-home.com/forum/download/file.php?id=15384

X1 speed, DVD-R

![image](https://user-images.githubusercontent.com/20796334/88054010-93779300-cb54-11ea-8ef4-569dd9dfb3a2.png)

**Comment by yoosf9760** [comment]
What is the name of the program used in the burning process?

**Comment by Fran7Ribeiro** [comment]
> What is the name of the program used in the burning process?

CDBurnerXP

**Comment by yoosf9760** [comment]
![٢٠٢٠٠٧٢٢_٠٠٠٤٣٤.jpg](https://user-images.githubusercontent.com/68129027/88101448-0ca3d400-cbaf-11ea-8217-81138c1ec3f2.jpg)
    

Is this good

**Comment by Fran7Ribeiro** [comment]
> ![٢٠٢٠٠٧٢٢_٠٠٠٤٣٤.jpg](https://user-images.githubusercontent.com/68129027/88101448-0ca3d400-cbaf-11ea-8217-81138c1ec3f2.jpg)
> 
> Is this good

Exactly

**Comment by yoosf9760** [comment]
Same for problem cannot read dvd

**Comment by Fran7Ribeiro** [comment]
If it shows the error that you cannot read then the problem may be your laser.

**Comment by CTurt** [comment]
Glad you were able to solve the issue!
