### ISSUE TITLE
My PS2 is only reading games. And is not playing any DVD movie. 

### ISSUE THREAD

**Issue by 14saleh14** [CTurt/FreeDVDBoot#129]
My PS2 is only reading games. And is not playing any DVD movie. Games are working great so the lens is fine.

I burned the All Slim models

But it said "The disc could not be read"

Error message
![15956204482698717424864443241207](https://user-images.githubusercontent.com/68755211/88430143-9e565000-ce00-11ea-8f88-8e925e160d3c.jpg)

PS2 serial and versions
![15956205188139212181858362550734](https://user-images.githubusercontent.com/68755211/88430241-c5148680-ce00-11ea-8774-de600def867c.jpg)

When I inserted a dvd movie this screen comes after a long black screen
![15956206063539120023775027607216](https://user-images.githubusercontent.com/68755211/88430359-02791400-ce01-11ea-9e92-6237fa784341.jpg)

Please help

**Comment by CTurt** [comment]
Laser issue. You can try calibrating the laser (Diagnosis option in the Version settings), but if your console still isn't able to read DVDs, then it will need to be replaced probably.
