### ISSUE TITLE
2.10 U support?

### ISSUE THREAD

**Issue by Skedable** [CTurt/FreeDVDBoot#136]
The majority of the PS2s that I have access to, (Including my own PS2) have dvd version 2.10 U. I would love to use this amazing piece of software, and some games have better compatibility with older PS2 models. (ex. Jack X.) Is there any chance that support for this version can come in the future?

**Comment by CTurt** [comment]
Done.

https://github.com/CTurt/FreeDVDBoot/tree/master/PREBUILT%20ISOs
