### ISSUE TITLE
3.11 does NOT work with Japanese language

### ISSUE THREAD

**Issue by zacchi4k** [CTurt/FreeDVDBoot#14]
The README says:

> 3.11 (all regions EUMACDGJ) - confirmed working on hardware by MrMario2011, and others. Language setting doesn't seem to matter ([Japanese language works at least](https://twitter.com/kood_infothief/status/1277600247024238592)).

However, the tweet that is linked when translated (I know a bit of Japanese) says:

> SCPH-90000, FreeDVDBoot 3.11EU.iso _[now called 3.11EUMACDGJ.iso]_
If the language is _[set to]_ Japanese, black screen. If the language is changed to English, uLE boots.
With 3.11J.iso, black screen _[now irrelevant since it was removed]_

The video linked in the tweet also shows that

**Comment by CTurt** [comment]
Lol my bad - I think I need some sleep. Will update README, thanks!
