### ISSUE TITLE
Black screen on SCPH-39001 (PS2 phat)

### ISSUE THREAD

**Issue by Gamermanner** [CTurt/FreeDVDBoot#140]
So I used the 2.10 iso, burned it to DVD+R with ImgBurn, 2.4x writing speed, tested it out both verified or not, I only managed to get a black screen. Any suggestions? Let me know. Thanks.

SCPH-39001 (DVD Player: 2.12U)

Edit: I've tried using CDBurnerXP, 1x writing speed, but unfortunately I managed to get the same result.

**Comment by hansi122435** [comment]
First of all: Currently only 2.10 is supported, not 2.12. Instead of using DVD+R please use DVD-R

**Comment by Gamermanner** [comment]
Never mind, since CTurt uploaded 2.12U ISO, I have finally managed to get it working.
:)

**Comment by hansi122435** [comment]
You are in luck :+1: This (fast) move surprised me as well
