### ISSUE TITLE
Black screen on 2.10E, SCPH-30004 R

### ISSUE THREAD

**Issue by Mare555333** [CTurt/FreeDVDBoot#144]
I burned DVD-R disc at lowest speed in ImgBurn, PS2 has recognized disc as DVD Video, I select it, and after that, black screen shows up. I waited over 5 minutes do load it and nothing.

**Comment by Mare555333** [comment]
SCPH-30004 R, not SCPH-30001 R, sorry

**Comment by hansi122435** [comment]
Try another burning-program and check "finalize". Your console is supported and already confirmed.

**Comment by bigfloppa** [comment]
CDburnerXP worked for me, with the compatibility mode selected, finalize disc and 1x speed. I'm using 2.10A

**Comment by Mare555333** [comment]
I tried that, but it doesn't work.

**Comment by Mare555333** [comment]
After long time, I tried and it works! You need to burn ISO from a old commit https://github.com/CTurt/FreeDVDBoot/tree/6d4efb401b0a69a2f84b62760a463f148961e702
