### ISSUE TITLE
Does not work on 2.12U

### ISSUE THREAD

**Issue by gdundee** [CTurt/FreeDVDBoot#145]
The readme says that the 2.12U version is supported, but I am just letting you know that it does not work.  :(  I have burned 4 dvds 4 separate ways.(I used both dvd burning software)  I have unplugged controllers, memory cards, and I tried unplugging the usb drive.  I always get a black screen.  I verified my console will play dvds.  My PS2 Phat information is listed below:

Console SCPH-39001
Browser 1.20
CD Player 1.20
PlayStation Driver 1.10
DVD Player 2.12U

**Comment by hansi122435** [comment]
Unplug your Memory Card(s) and try again. Which kind of blank DVD did you use? Did you finalize the disc?

**Comment by xeons** [comment]
Same. I could hear it reading the disk for a good 10 minutes before I stopped it. I don't think it's a weak laser because it has no problems reading DVD movies and PS2 games.

**Comment by PorterGiles123** [comment]
Same here as well, despite this recent tweet https://twitter.com/CTurtE/status/1293319847267401737.
You can see he is using the same machine as the one specified above:

Console:  SCPH 3900-1
Browser:  1.20
CD player: 1.20
Playstation driver: 1.10
DVD player: 2.12U

I don't doubt the sincerity of the poster of this video, but it is frustrating to see how someone else has gotten it to work and we are all stuck here.

However, I noticed that this video was posted on the 11th, the day of the first 2.12 commit. Xeons and gdundee, you guys tried this yesterday. There was another commit on the 12th which means that the code you are trying is different than the code the person in this video was using. At closer examination there didn't seem to be very many changes in the two commits but enough to make me want to try the commit 6d4efb401. So I downloaded that one, burnt it and it seems to be working. This is all happening real time though so I will let you know if I find out more. 

If you are not familiar with how git works here is a link to that commit: https://github.com/CTurt/FreeDVDBoot/tree/6d4efb401b0a69a2f84b62760a463f148961e702

You know, it is very funny to see other people trying to do this at the same time as me. Most of the projects I do are usually pretty old and don't have a very active community.

**Comment by PorterGiles123** [comment]
Can Confirm! Successfully installed using the 2.10 iso from the above stated commit. 

After about 4 failed DVD+R tries I found out that you must revert to the older commit in order for your 2.12U system to work properly. It seems as though they made some changes to the code base since the 11th that have made newer versions not work with 2.12U. Try checking out the commit 6d4efb401b0a69a2f84b62760a463f148961e702 and finding the file called "some 2.10 models and 2.12U.iso". Use this one instead of the newer version. 

the first time I tried with this older commit version I got a "Tv system doesnt match" error. I restarted the ps2 and it booted up perfectly.

Amazing, I am so excited to play some long lost games.

also they should probably look into what changed between the two commits and maybe consider having a seperate 2.12U if this error persists.

**Comment by xeons** [comment]
Success! the old commit version worked!

**Comment by hansi122435** [comment]
> Success! the old commit version worked! I already have FreeMCBoot but I just wanted to see a burned disc boot code on my vanilla PS2 as geeky as that sounds.

Well, i can understand you :D At the moment i'm bidding on "new" old & used ps2 consoles on ebay. The interesting thing: there are already 4 consoles in my possession :D :D :D

**Comment by gdundee** [comment]
Heck yeah!  I'll try this when I get home!  Thanks for finding this!!

**Comment by Mare555333** [comment]
> Can Confirm! Successfully installed using the 2.10 iso from the above stated commit.
> 
> After about 4 failed DVD+R tries I found out that you must revert to the older commit in order for your 2.12U system to work properly. It seems as though they made some changes to the code base since the 11th that have made newer versions not work with 2.12U. Try checking out the commit [6d4efb4](https://github.com/CTurt/FreeDVDBoot/commit/6d4efb401b0a69a2f84b62760a463f148961e702) and finding the file called "some 2.10 models and 2.12U.iso". Use this one instead of the newer version.
> 
> the first time I tried with this older commit version I got a "Tv system doesnt match" error. I restarted the ps2 and it booted up perfectly.
> 
> Amazing, I am so excited to play some long lost games.
> 
> also they should probably look into what changed between the two commits and maybe consider having a seperate 2.12U if this error persists.


Maybe is no connection to that, but I have to ask. Is it possible to apply this old commit on 2.10 E, because I have a same problem (black screen and that)?

**Comment by xeons** [comment]
> 
> 
> > Can Confirm! Successfully installed using the 2.10 iso from the above stated commit.
> > After about 4 failed DVD+R tries I found out that you must revert to the older commit in order for your 2.12U system to work properly. It seems as though they made some changes to the code base since the 11th that have made newer versions not work with 2.12U. Try checking out the commit [6d4efb4](https://github.com/CTurt/FreeDVDBoot/commit/6d4efb401b0a69a2f84b62760a463f148961e702) and finding the file called "some 2.10 models and 2.12U.iso". Use this one instead of the newer version.
> > the first time I tried with this older commit version I got a "Tv system doesnt match" error. I restarted the ps2 and it booted up perfectly.
> > Amazing, I am so excited to play some long lost games.
> > also they should probably look into what changed between the two commits and maybe consider having a seperate 2.12U if this error persists.
> 
> Maybe is no connection to that, but I have to ask. Is it possible to apply this old commit on 2.10 E, because I have a same problem (black screen and that)?

It may work, because whatever refactoring was done recently seems to have broken everything.

**Comment by gdundee** [comment]
The old commit https://github.com/CTurt/FreeDVDBoot/commit/6d4efb401b0a69a2f84b62760a463f148961e702
works flawlessly with 2.12U 😊

**Comment by Mare555333** [comment]
I tried and it works! Finally!

**Comment by CTurt** [comment]
Thanks for your report, I've put the old image that was confirmed working back.
