### ISSUE TITLE
Running backups without going through UlaunchELF menu on 2.10

### ISSUE THREAD

**Issue by bigfloppa** [CTurt/FreeDVDBoot#146]
I am aware of the FDVDB ESR Patcher GUI and know that it works with 3.10 which it comes with, however all of my attempts with following instructions given on this site and others, as well as trying to load the files from the iso into the patcher payload folder have just resulted in the disc being detected as a DVD, in that it goes into the dvd menu, and shows the message that it is not able to be read. ULaunchELF works perfectly on my console.

**Comment by hansi122435** [comment]
What exactly did you accomplish? Did you use FDVD ESR Patcher or manually?

**Comment by bigfloppa** [comment]
That's alright, I thought the same. I guess I will try to contact the creator/s of this patcher. If anyone knows them it would be beneficial for many of us to have this program updated with the new isos that have come out!

**Comment by CTurt** [comment]
I don't maintain ESR, sorry. They need to update it.
