### ISSUE TITLE
SCPH-77004 - DVD Player 3.11E doesn't boot the DVD

### ISSUE THREAD

**Issue by orakless** [CTurt/FreeDVDBoot#154]
I tried three different softwares (cdrecord/k3b on my Linux, and I installed Windows to use CDburnerXP (with compatibility mode checked) and ImgBurn). All the same result: Unable to read disc. The console can read real DVD thought.

**Comment by mheiniger** [comment]
My console can read real DVD's, but it can't read a (DVD-R) copy of a real DVD.

**Comment by lvlhead** [comment]
What brand media are you using? What is the lowest speed you can burn at?

**Comment by orakless** [comment]
> What brand media are you using? What is the lowest speed you can burn at?

Verbatim, 8x

**Comment by hansi122435** [comment]
The 77004 consoles are 100 % confirmed to work. The problem must be on your side. If you use Linux (Mint), just try the default burning program. Check if your system language is set to English.
