### ISSUE TITLE
mass:/ is empty

### ISSUE THREAD

**Issue by rosenishere** [CTurt/FreeDVDBoot#159]
mass:/ is empty. I have OPL on my flash drive, but mass:/ seems to have nothing in it.

**Comment by FadilCox** [comment]
I had this same issue. Try formatting flash drive to fat32 or fat, or use another flash drive. Also try out both usb ports.

**Comment by hansi122435** [comment]
As @FadilCox said ... Try a fresh FAT32 formatting or use another flashdrive (USB 2.0 is often more compatible than 3.0/3.1)

**Comment by rosenishere** [comment]
I fixed my issue. It has to be mbr and fat32, BUT you have to use this formatter: http://www.ridgecrop.demon.co.uk/guiformat.exe
