### ISSUE TITLE
The Prebuilt All Ps2 Slims ISO (with uLaunchelf) Doesn't Work But FreeDVDBoot Patched Games Do.

### ISSUE THREAD

**Issue by RinasSam** [CTurt/FreeDVDBoot#163]
I have used the FreeDVDBoot ESR Patcher by Jabu to patch some games.
I Burned them to dvd-r's and they worked.
When I tried to use the prebuilt ISO (with ulaunchelf), my ps2 doesn't start it. Instead, it just goes to the browser.

PS2 Model: SCHP-90006
Region: NTSC-J
Date Code: (Missing)

Software Used: IMGBurn
Disc Burning Speed: 4x
DVD-R Brand: BINGO

Also, my PS2 has a habit of only being able to boot into discs. 
That means that if I try to insert a disc without rebooting the PS2, nothing will happen and it will stay stuck on "reading disc".

Any help or explanation as why the prebuilt ISO is not working would be appreciated.

**Comment by ghost** [comment]
i have same problem if you found a way please keep me in touch

**Comment by RinasSam** [comment]
I found the 2 main issues that caused this (at least for me).
1-Dying laser.
2-Modchip issues. Apparently it has to be run in DVD Movie mode.

Though I still do not understand why do ESR FreeDVDBoot patched games work normally.

**Comment by RinasSam** [comment]
I think this deserves to be closed, for now.
