### ISSUE TITLE
Disc stays blank. 2.10A

### ISSUE THREAD

**Issue by jamesy0ung** [CTurt/FreeDVDBoot#185]
Hi. I have burned the 2.10 iso and it just keeps me at a blank screen. I have been waiting for 5 minutes and it still does nothing. I have played a DVD movie to check the laser. My console dvd player version is 2.10A. I burned it using CDBurnerXP at 1x speed with compatibility enabled and finalise enabled. I also checked verify dvd and it passed successfully. Help please as I do not have many DVDs left.

**Comment by jamesy0ung** [comment]
This is fo F***ing irritating. I have tried another dvd drive with the same settings and it will not work _STILL_.

**Comment by J013k** [comment]
Maybe this might be more helpful:
https://www.psx-place.com/threads/update-3-meet-freedvdboot-by-cturte-partial-first-ps2-fat-phat-model-supported.30204/page-10#post-261021.

Additionally.
What is your console revision?

From README.md:

> 2.10 (certain models only?
>Working: SCPH-30001 R (ROMGEN 0160AC20010427),
>SCPH-30000 (ROMGEN 0160JC20010427), SCPH-30004 R (ROMGEN 0160EC20011004),
>**Not working**: SCPH-39004 - todo),

**Comment by jamesy0ung** [comment]
Thanks

**Comment by jamesy0ung** [comment]
Also I have SCPH-30002

**Comment by J013k** [comment]
Last thing that comes to my mind...
You have Samsung SH-222BB:
https://github.com/CTurt/FreeDVDBoot/issues/183#issuecomment-731626893.

So there is no way that firmware of this writer should allows to write DVD-+R disc at 1x speed.
While writing\burning you should saw what speed of writing you actually had:
![https://www.eui.eu/Images/ServicesAdmin/Computing/CDBurnerXPProgress2.jpg](https://www.eui.eu/Images/ServicesAdmin/Computing/CDBurnerXPProgress2.jpg)

What brand of discs did you use?
Did you use DVD-R or DVD+R discs?

**Comment by jamesy0ung** [comment]
I used Verbatim DVD-R 16x and Digimax DVD-R 16x. I also tried a USB SuperDrive.
Also the lowest supported speed was 4x, but i went to other and selected 1x.
The writemaster crap in the drive probably wrote it at a higher speed

**Comment by TnA-Plastic** [comment]
The "burn as slow as possible"-MYTH is just flat out wrong... Burn at mid-speed of the speed-range!
Also rather use IMGBurn and turn "perform OPC" in its write-settings ON!
