### ISSUE TITLE
Is 3.11G SCPH90006 NTSC-J Supported?

### ISSUE THREAD

**Issue by xWends** [CTurt/FreeDVDBoot#188]
Hello, may I ask if the Japanese slim ps2 scph90006 are supported? I want to install funtuna on it and fmcb to boot games from hdd since my optic drive doesn't work or it is conflicting with it's modchip, the modchip was Super7 e17 and also don't know how to go to bios to enable or disable it, I also burned the freedvdboot on a CD not DVD, am I doing something wrong? please help!

**Comment by J013k** [comment]
https://github.com/CTurt/FreeDVDBoot/blob/master/README.md.

**Comment by xWends** [comment]
> https://github.com/CTurt/FreeDVDBoot/blob/master/README.md.

please can you tell me if it's YES or NO? because I don't really understand this kind of modding.

**Comment by J013k** [comment]
Just put a minimum of effort into it.
Please, read the first verse about compatibility with SLIM consoles.
How hard it can be?
If you don't understand the first verse, how are you going to deal with installing\setting Fortuna later?

Also the info which type of a disc you need to choose is written under "Easy setup for all PS2 Slim consoles / Bravia TV"
Second dash.

So all the info that you want are in these two verses, almost at the beginning of this document. 

Best regards.

**Comment by xWends** [comment]
sorry I'm just kind of frustrated since it's my first time modding a PS2 and did not really read carefully the documentation but with the help of google and youtube I figured it out and installed it right away. thanks for the answer btw
