### ISSUE TITLE
disc could not be read 3.11E

### ISSUE THREAD

**Issue by g3rwy** [CTurt/FreeDVDBoot#190]
I recently tried to make backups of some games because my older discs were barely working.
I did everything that was said in custom discs for PS2 Slim, but every time its saying The disc could not be read, even with diagnosis On and gamepad plugged off and on.
I tried DVD with some video and it worked fine so its not the laser (console is old but i didnt used it for very long time)
I used DVD-R for burning.
My PS2 version:
SCPH-77004
Browser 1.40
CD Player 2.00
PS Driver 2.00
DVD Player 3.11E

Its unmodified and dont have FreeMCBoot memory card.
Im also using Macbook, so if anyone want to share some esr patchers only for Windows then i will just give up and try to install FMCB.
But my main goal was to make backups on DVD.

**Comment by g3rwy** [comment]
Okay i will try another ESR patcher on my old Windows Laptop, maybe thats the issue, but something telling me my files in directory are bad placed, or PS2 dont see VIDEO_TS

**Comment by g3rwy** [comment]
Still nothing. I tried FDVDB ESR Patcher GUI by Jabu and its still not working.
Is it worth to go with this method or just install FMCB on memory card and try to launch backup with this?

**Comment by TheAwesome98-Real** [comment]
~~AFAIK 3.10 is the highest supported version, the 3.11 isn’t supported~~

EDIT: it has been supported since I last check so I’m wrong sorry haha

**Comment by g3rwy** [comment]
Well it worked for me, I just needed to turn on OPC before writing on ImgBurn, but my laser in PS2 is old and probably not working, so its not FDVDB issue sorry.

**Comment by milecile** [comment]
Hello.

I have a ps2 slim, scph75004 with DVD Player 3.11E

the issue is, that the freedvdboot disc could not be read

im using verbatim dvd-r and tried also with different burning tools
i tried with burning speed 1x and also 4x

Any idea how to fix this?
