### ISSUE TITLE
2.12U does not work

### ISSUE THREAD

**Issue by SavnoorSamra** [CTurt/FreeDVDBoot#2]
I see that it isn't supported yet but I just wanted to confirm it does not work.

to the wonderful developer: Are you planning to make versions for other versions as well? I know you said you "might" but seeing how this project has had such a positive reaction, it would be much appreciated if you would. Or if you could explain how we could make it for our own systems?

**Comment by fireether** [comment]
He has a blog here about it: https://cturt.github.io/freedvdboot.html - I'm still digesting it. Just got introduced to Ghidra by that. Thank you @CTurt, keep up the good work.

**Comment by CTurt** [comment]
Yeah, I think I'm going to do more versions. Today I uploaded a hybrid ISO that supports both 3.10 and 3.11. Will try to add more
