### ISSUE TITLE
"The disc could not be read" SCPH-75004

### ISSUE THREAD

**Issue by ResKraven** [CTurt/FreeDVDBoot#209]
I've tried many times to play the burned DVD-R with all the different methods proposed in the "Troubleshooting" section, and my ps2 can easily read dvd's.
I currently have a desktop PC with an "HL-DT-ST DVDRAM GH24NSD1 LG00-20" as described by ImgBurn.
The Iso that I've burned is the "All PS2 Slim" one in a "Verbatim" DVD-R. I've also tried with a DVD+RW but it didn't work.
![IMG_20210208_191044](https://user-images.githubusercontent.com/75739754/107263148-b52d5e80-6a41-11eb-985d-96c4f2f4728d.jpg)
![IMG_20210208_191112](https://user-images.githubusercontent.com/75739754/107263151-b65e8b80-6a41-11eb-948a-4560aaa43e15.jpg)

**Comment by APrettyCoolUser** [comment]
it also happened to but i have model SCPH-90004

**Comment by ResKraven** [comment]
I'm afraid that the "9000" models are unmoddable via software.
I think you'll have to buy a modchip.

EDIT: Sorry I didn't see all the issues here that involves your model and I think that this one in particular could be of help.
https://github.com/CTurt/FreeDVDBoot/issues/177

> it also happened to but i have model SCPH-90004

**Comment by ResKraven** [comment]
Good news!
Solved it myself utilizing a different type of DVD-R.
Guess "Verbatim" is a little crappy.
