### ISSUE TITLE
Dvd software version not showing up on pcsx2? 

### ISSUE THREAD

**Issue by darkblood159** [CTurt/FreeDVDBoot#21]
![ps2 image](https://user-images.githubusercontent.com/53360355/86199018-d625ec80-bb0d-11ea-9f1b-72501d6e534d.jpg)
is the dvd software version supposed to show up on the emulator? im using the same bios files for my emulator that my real console has. i am trying to fix up a 3.02 version of freedvdboot.

**Comment by parkerlreed** [comment]
The emulator doesn't include the DVD player code. The blog post explains that this is encrypted and has to be extracted from a  real console to then decrypt and use in the emulator.

**Comment by edo9300** [comment]
It would be helpful if there was a little guide on how to set up the emulator from dumps, as that'd make porting easier for other people, as it seems that in the end it would probably be just relocating the functions in the payload, I too have a scph-39004 with version 2.13E and I have already decrypted the dvdelf, what I don't manage to do is make that elf properly bookable, as from what the blog post does, it has no elf header, and what I don't manage to do is repack this elf to make it loadable in ghidra and bootable in pcsx2
