### ISSUE TITLE
Running games on the burned dvd

### ISSUE THREAD

**Issue by MrAwezom3** [CTurt/FreeDVDBoot#22]
I've seen the issue #18 but I think he wants to run games off of the flash drive, I just want to recreate the demo that CTurt youtube video where he run the shadow of the colussus without running the uLaunchELF. Just like the normal ps2 dvd. I dont want to modify my current ps2.

**Comment by darkblood159** [comment]
i believe he did modify his ps2 with freedvdboot. i believe you can set up homebrew to auto launch burned discs... i could be wrong though.

**Comment by anisiovalverde** [comment]
He describes the process on his blog and you at this moment need to have C program language skills to make it possible https://cturt.github.io/freedvdboot.html

**Comment by MrAwezom3** [comment]
Sorry, I did not see that early. I might try these.

**Comment by zacchi4k** [comment]
The process is really complex tho, I recommend you get a second memory card and install FMCB (assuming it's a compatible model) and ESR on it, then just use the usual method with ESR Patcher. Or alternatively you could use OPL.

And if you're worried about breaking your console, it's _impossible_ to do so with FMCB

**Comment by ADoomedSpaceMarine** [comment]
I was able to patch an iso, but it required editing the binary files and the patcher's raw hex data. It's pretty straightforward if you KNOW how to search for what he mentions, but it's certainly work.

**Comment by MrAwezom3** [comment]
It certainly is a porting project. The notes he shows that he modify the binary of VIDEO_TS.BUP created by ESR patcher and copied some data from VIDEO_TS.IFO to his own VIDEO_TS.IFO

**Comment by war3zlod3r** [comment]
I too am interested in trying this I know he doesn't make a tool to support it but trying to follow the instructions he left I was unable to find the values listed in the files in my hexeditor. Probably just looking at this wrong but would love if someone would provide more detailed information on the process.

**Comment by VersatileNinja** [comment]
I'd love to help too if someone with more expertise can guide us.

**Comment by ADoomedSpaceMarine** [comment]
Good to hear. Welcome to the club. If you add my discord I can get you in a group with a few others who are doing the same. DanSr#7935

I'm just about to sign out for the night. Family comes first on the fourth. I'll add those of you interested when I get home tonight. Have a good one, hopefully we can get some collective effort and get some done.
