### ISSUE TITLE
2.10A/1.30A support

### ISSUE THREAD

**Issue by jamesy0ung** [CTurt/FreeDVDBoot#23]
Hi is it possible for a 1.30A or 2.10A (I have the upgrade disc still) version.
Thanks for the awesome project @CTurt

**Comment by bonexd** [comment]
yes if you add it yourself, its not as simple as just _adding support_

**Comment by jamesy0ung** [comment]
I did read the porting notes but they are a bit technical. I'd be happy to do it if the guide was easier to do (screenshots)

**Comment by jamesy0ung** [comment]
Hey does anyone know if the current 2.10 iso works on SCPH-3002
