### ISSUE TITLE
SCPH-77004 "Unable to read disc"

### ISSUE THREAD

**Issue by theblurry99** [CTurt/FreeDVDBoot#236]
When I try to run backups booted using FreeDVDBoot, the disk spins for few seconds and then shows an error saying "Unable to read disc".

Yes, my console is set to English
Yes, I've done the same steps of burning the disk
No, my laser is not defective (original games, DVD movies and Audio CDs are read fine)

Tried many programs (ImgBurn, CDBurnerXP) but nothing seems to work.

I managed to get into a game of "Crash Twinsanity" once and saved my progress, now this disc cannot be read.

Also I tried using different disks and disk brands, nothing.

I would really love to see some possible solutions!

**Comment by theblurry99** [comment]
> When I try to run backups booted using FreeDVDBoot, the disk spins for few seconds and then shows an error saying "Unable to read disc".
> 
> Yes, my console is set to English
> Yes, I've done the same steps of burning the disk
> No, my laser is not defective (original games, DVD movies and Audio CDs are read fine)
> 
> Tried many programs (ImgBurn, CDBurnerXP) but nothing seems to work.
> 
> I managed to get into a game of "Crash Twinsanity" once and saved my progress, now this disc cannot be read.
> 
> Also I tried using different disks and disk brands, nothing.
> 
> I would really love to see some possible solutions!

Just tested, the prebuilt ISO from github doesn't work either.

**Comment by ErikKrak** [comment]
Yep, same for me, all of the above. Did you somehow manage to get it working? I tried to set my PS2 up for nearly 5 hrs at this point with OSSC and such, just to get to this. Bummer.

**Comment by wjanes** [comment]
I can confirm its working on this version. i have used cdburnerxp as described. The first time it didnt work, then i cleaned the laser with spiritus and a cotton swap. Afterwards it worked out of the box :)

**Comment by theblurry99** [comment]
Iasue resolved by DVD laser adjustment as seen here https://youtu.be/0tvwdel1XuA, closing issue!
