### ISSUE TITLE
Unable to read disc.

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [CTurt/FreeDVDBoot#244]
I tried to run FreeDVDBoot on my PS2, I burned the disc at 4x speed with ImgBurn on a Maxell DVD-R, I got an unable to read disc error upon launching into DVD Video, I used my last DVD-R (also maxell), I burned it with 3x speed on CDBurnerXP. Put it in the PS2, unable to read.

I've tested with a real DVD Video, it was able to play fine.

The PS2 is an SCPH-75001

**Comment by Fahaddex** [comment]
my ps2 has tthe same problem

**Comment by Lost-Entrepreneur439** [comment]
hey well i found a fix, cover up the disc drive sensors with tape, put the disc in the PS2 (BEFORE turning it on), and try booting it up with the disc drive open. fixed it for me.

**Comment by Fahaddex** [comment]
thanks ill try it out
