### ISSUE TITLE
Unable to Read Disc - 77001, 3.11U

### ISSUE THREAD

**Issue by floppyjay** [CTurt/FreeDVDBoot#257]
77001, 3.11U
The majority of discs (DVD-R,DVD-RW,DVD-R DL) burned do not show a DVD symbol in the Browser of the ps2, and instead read an error "The disc could not be read". These were made at various write speeds using various software and various suggested tweaks to the settings of said software, using various DVD recorder drives (built in and external) and brands of dvd including Verbatim,Maxell, and  windata. The ISO used was the "ALL ps2 slim" iso and also one try was an older version-the "(hybrid) 3.10/3.11" iso.

2 attempts with the exact same settings (CDBurnerXP at 1x write) show a similar albeit different error, as the "DVD Video" shows up in the ps2 browser, but upon pressing X on the DVD icon, a black screen then "Unable to read disc" shows up. 

Legitimate DVDs and PS2 games work. Using Language English, Diagnostic mode on.

Ran out of DVDs and frustrated. Not sure if there is an answer, but please ask me if more information is needed to troubleshoot.

**Comment by alexs3112** [comment]
I don't know if it helps but yesterday I tried it on a 77004 3.11E and it worked with 1x speed DVD+R and the hybrid ISO, I used ImgBurn. At first, I forgot to set my consoles Language to English, but after I did, it worked 1st try.

**Comment by floppyjay** [comment]
Tried on different DVD burner with updated All slims iso and it worked! Amazing job! Always try a different DVD burner if you ever so possibly can.
