### ISSUE TITLE
SOLVED - PS2 Slim -SCHP-77002 - The Disc Cannot be Read

### ISSUE THREAD

**Issue by albusorus** [CTurt/FreeDVDBoot#287]
PS2 Info
--------------
PAL
Console: SCPH-77002
DVD Player 3.11A
-------------

Discs used was a Verbatim 16x DVD-R burned on lowest speed possible (3x)
Burned in both IMGBurn and CDBurnerXP, validated, finalised, compatibility on
used: all ps2 slims .iso

English language
cleaned ps2 laser
Diagnosis on
Memory cards removed
Controller removed
Played a video dvd and worked fine, no clicking noises aswell.
multiple discs burned all same problem

Am i doing something wrong, is 3x write speed still too high
Any help would be apreciated!

**Comment by albusorus** [comment]
I've bought some new disks, coming in the mail now
Old Stock Verbatim 4x DVD-R

Will let you know if they work!

**Comment by albusorus** [comment]
Update, the new Disks Work!, They are verbatim 8cm 4x speed disks, i wrote the iso at 1x speed and it worked first try. It seems very important to write at 1x. Bought from ebay however im in Australia!

![s-l500](https://user-images.githubusercontent.com/101624151/159652737-a5db6e1f-f558-499b-8119-dd562304c98b.jpg)
.

**Comment by Bra-Arg** [comment]
Quiero ayudar a los que me leen y también dar información a@CTurt.
Me funcionó grabar FreeDVDBoot en un **DVD+RW de Verbatim**. Lo hice con ImgBurn a velocidad 4x.

Edit: Olvidé aclarar que funcionaba en una PS2-Slim modelo 79001. DVD versión 3.11U
