### ISSUE TITLE
blank screen using free dvd boot 

### ISSUE THREAD

**Issue by Algamerthetruealbanian** [CTurt/FreeDVDBoot#3]
DVD driver 3.11E 
any other info you want i can provide
i just took the premade iso and burned it 
im doing somthing wrong here
plz help i wasted a dvd i dont have much left

**Comment by zacchi4k** [comment]
Did you set your language to English?

**Comment by CTurt** [comment]
Can your PS2 read other DVDs? Are you using DVD-R, and did you finalize the disc when burning? Could also try verifying the burn

**Comment by Fighter19** [comment]
Hello,
I can confirm,
PS2 stuck with black screen using the prebuilt hybrid ISO.
3.11E; Language set to English.
Will try again with newer model.

**Comment by Fighter19** [comment]
@Algamerthetruealbanian 

Have you tried letting it load for a longer period of time?
I had to let it load for about 3 minutes before I got into uLaunchElf.
It seems the disc drive is just a bit damaged.

**Comment by mayank2gud** [comment]
Hello,
Im getting stuck on Black Screen and sometimes it shows "Disk cannot be read error"
Version SCPH-90004
DVD Player 3.11 E
Any help is well appreciated

**Comment by CTurt** [comment]
I think all of these problems are just related to old disc drives. There's not a huge amount I can do. The tip to wait a few minutes if on a black screen is helpful, I'll add that one to the readme

**Comment by sestain** [comment]
I had black screen when I had my memory card in then I tried without memory cards and it started working just fine

**Comment by CTurt** [comment]
Interesting, can add that to README too.

**Comment by ghost** [comment]
> @Algamerthetruealbanian
> 
> Have you tried letting it load for a longer period of time?
> I had to let it load for about 3 minutes before I got into uLaunchElf.
> It seems the disc drive is just a bit damaged.

are you say black screen is gone and in main menu  of ps2 to wait???

**Comment by Fighter19** [comment]
No, I had to wait about 3 minutes on a black screen, before the uLaunchElf became visible.

**Comment by ghost** [comment]
for me just black screen shown and gone then go to memory card part that you known for manging game saves, even i remvoe it the same result

**Comment by ghost** [comment]
> No, I had to wait about 3 minutes on a black screen, before the uLaunchElf became visible
whar is your ps, tv, dvd, freedvdboot version, and steps you do

**Comment by llkkx** [comment]
Hello,
The ps2 is not reading the disc already calibrated the laser I tested a dvd and still not reading. Can someone help me?

Console "SCPH-77001"
Player "3.11U"

**Comment by gokdenizozkan** [comment]
My phat ps2:

    Model: SCPH-39004
    DVD Player version: 2.13E
    It does play original film dvds.
    It is not modchipped AFAIK.

FreeDVDBoot DVD

    Software used to burn: CDBurnerXP
    Burn speed: 4X, 1X (both tried)
    Burned file: Prebuilt ISO "Phat ps2s 2.10-2.12"
    Burn modes: First one VIDEO BURN (only VIDO_TFS file) and second one ISO BURN (ISO File)

So... it didn't work out.
VIDEO BURN did work and said "Your firmware is not supported" however with ISO, it stucked at black screen.

Is it okay to have black screen with ISO instead of the "not supported message" with VIDEO file?
**tried every solution given in Readme file.**

**Comment by Avasam** [comment]
> I had black screen when I had my memory card in then I tried without memory cards and it started working just fine

I concur. Removing my PS1 memory card from slot 1 fixed the black screen (none in slot 2)

**Comment by sestain** [comment]
> > I had black screen when I had my memory card in then I tried without memory cards and it started working just fine
> 
> I concur. Removing my PS1 memory card from slot 1 fixed the black screen (none in slot 2)

I had my PS2 Memory Card in Slot 1 (It was 8MB or 64MB)

**Comment by whomeoops** [comment]
Used CDBurner XP at 1x speed, DVD-R, took my memory cards out, just could not get it to work! Was trying the thing someone suggested about unplugging your controller and plugging it back in when on a whim I decided to put it in controller 2 instead of back into controller 1 and suddenly it decided to work! So there's another tip for someone else in the future having issues with it to try

**Comment by trappitaro** [comment]
Doesn't work on my ps2 black screen....

**Comment by cIickclack** [comment]
My ps2 slim PAL model SCPH 70003 DVD player 3.10E, can see it on browser as "DVD Video" but when I play it, it shows somekind of white artifact two times (Playstation2 logo) and blackscreen, tried waiting for hours Ulaunchelf doesn't show up. I've burnt 6 DVD-R verbatim discs already, not one worked. It can run original GTA 3 game disc and it's badly scratched. Also tried to put DVD movie but it's region 1 ntsc-u it says "Disc cannot be played due to regional restrictions" so I assume laser is good? or is it worn out?

**Comment by andreipiper** [comment]
> My ps2 slim PAL model SCPH 70003 DVD player 3.10E, can see it on browser as "DVD Video" but when I play it, it shows somekind of white artifact two times (Playstation2 logo) and blackscreen, tried waiting for hours Ulaunchelf doesn't show up. I've burnt 6 DVD-R verbatim discs already, not one worked. It can run original GTA 3 game disc and it's badly scratched. Also tried to put DVD movie but it's region 1 ntsc-u it says "Disc cannot be played due to regional restrictions" so I assume laser is good? or is it worn out?

Had the exact same problem, on the exact same PS2 and driver. This FIXED IT: https://www.psx-place.com/threads/freedvdboot-by-cturt.30220/

Go to this link and download the 3.10 only. Worked instantly. Hope this helps bro.

**Comment by retrorepair** [comment]
> > My ps2 slim PAL model SCPH 70003 DVD player 3.10E, can see it on browser as "DVD Video" but when I play it, it shows somekind of white artifact two times (Playstation2 logo) and blackscreen, tried waiting for hours Ulaunchelf doesn't show up. I've burnt 6 DVD-R verbatim discs already, not one worked. It can run original GTA 3 game disc and it's badly scratched. Also tried to put DVD movie but it's region 1 ntsc-u it says "Disc cannot be played due to regional restrictions" so I assume laser is good? or is it worn out?
> 
> Had the exact same problem, on the exact same PS2 and driver. This FIXED IT: https://www.psx-place.com/threads/freedvdboot-by-cturt.30220/
> 
> Go to this link and download the 3.10 only. Worked instantly. Hope this helps bro.

I've got the same slim, drive and problem (except it just always goes to black screen and then nothing forever).

Tried the 3.10 only iso, still won't work.

I am using a mini dvd-r as that's all I had lying around, does that make a difference do we think? I assume it must as tried everything in this thread and know the drive works fine.

**Comment by retrorepair** [comment]
Tried a dvd+r for laughs and also the hybrid iso, can't work it out
