### ISSUE TITLE
3.11a doesnt load

### ISSUE THREAD

**Issue by telostia** [CTurt/FreeDVDBoot#30]
Hi, did anyone test on slim 3.11a? I got my silver slim ps2 in Australia, console scph-77002 browser 1.40, cd player 2.0, ps driver 2.0, dvd player 3.11A. Tried prebuilt 3.11 iso and it just went to red screen saying insert ps2  format disc

**Comment by ADoomedSpaceMarine** [comment]
What burner did you use, what speed, discs, etcetera? It SHOULD see it as a DVD video if the versions match and the burn was successful and at a really slow burn rate. I can't attest to this as I am currently trying to figure out how to possibly find the stuff to make a version for 3.0, but yeah, if all was in place I don't know.

**Comment by telostia** [comment]
Burnt at 4x, now its saying the disc could not be read, i burnt it with samsung external usb burner, reads fine on pc though. Ill try 1x which is lowest it can go  i think. Its a Phillips dvdr probably single layer

**Comment by ADoomedSpaceMarine** [comment]
Interesting. Yeah, unfortunately my burning setup only allows 4x, so it may be contributing to it not cooperating. I would do just that, try to burn at the slowest possible speed and see where that gets you. Also, don't us RW's I couldn't even get the disc to spin up.

**Comment by telostia** [comment]
Damn only 3x is lowest. Burning now. fingers cross 😂

**Comment by telostia** [comment]
Stil no go. I dont think 3x is the issue though as game disk works fine. Stil saying the disc could not be read

**Comment by ADoomedSpaceMarine** [comment]
Was it a "read halted due to malfunction" error?

**Comment by telostia** [comment]
Nope 'the disc could noy be read' error

**Comment by telostia** [comment]
Oh what! It works now, i just had to open lid and close it. It loads...

**Comment by ADoomedSpaceMarine** [comment]
Weird, huh, I guess my issue is much different. Interadasting. Welp, I don't how to help. I just know it would be cool to get some people together that have MIPS and assembly experience to work on this so we can potentially pump out ports quicker.

**Comment by telostia** [comment]
Maybe memory cache from the 4x burn?

**Comment by telostia** [comment]
Ok gonna close this as solved. Burn at 3x! And make sure to reset console or reopen and close lid
