### ISSUE TITLE
Unable the read disc after first few successful time

### ISSUE THREAD

**Issue by grodzio1** [CTurt/FreeDVDBoot#301]
SCPH 30004 R, 2.10E dvd firmware.
I burned an image to a DVD using Linux's growisofs at lowest speed possible. The first few times it worked flawlessly, but later I started getting the "Unable to read disc" error. I've tried cleaning the disc, and it did not help. I've tried a different disc, on that one it took forever to read the disc and the drive made some pretty creepy sounds, so I gave up.

**Comment by ghost** [comment]
Try to play a DVD movie i hear that helps the lens regulate itself . If not , you could wipe the lens with isopropyl alcohol or adjust the potentiometers .

**Comment by grodzio1** [comment]
I got it working. I burned the .iso to a different DVD disc (Kaufland Classic DVD disc to be exact) using Nero on a Windows laptop. I've used the disc-at-once mode and 4x speed. Still doesn't explain why it stopped working on the first disc. Nonetheless, I consider the issue solved.
