### ISSUE TITLE
PS2 Reads Movies ,Games fine but won't read the FreeDVDBoot disc

### ISSUE THREAD

**Issue by Solua1** [CTurt/FreeDVDBoot#310]
PS2 Slim SCPH 75004 5D , dvd 3.11E

It reads all the games and movies i put into it but it refuses to load the disc with FreeDVDBoot 

90% of the time the "Unable to read disc" / "This disc cannot be played" error pops up but at times I can get past that with interchanging discs and when I do get past it nothing happens , it still doesn't read the disc instead presenting a fully black screen.
I waited for 30mins+ but still it didn't load FreeDVDBoot.

I'm using a DVD-R for the FreeDVDBoot disc burnt at the lowest speed and finalized.

Thanks for the help!

**Comment by ghost** [comment]
Hello,
I also had this problem. I first used freeisoburner. Then used cdburnerxp. With finalized and compatibility options enabled. Both at 4x speed. This worked one time with a Plexdisc DVD-R disc. Try a Verbatim DVD-R disc or DVD+R disc. Even try DVD-RW or DVD+RW. Try x1, x3, x4, x8, or x16 speeds. If this does not work, try a pot adjustment and turn the DVD laser a little counterclockwise to lower resistance of the laser and make it read burned discs.

**Comment by Solua1** [comment]
> Hello, I also had this problem. I first used freeisoburner. Then used cdburnerxp. With finalized and compatibility options enabled. Both at 4x speed. This worked one time with a Plexdisc DVD-R disc. Try a Verbatim DVD-R disc or DVD+R disc. Even try DVD-RW or DVD+RW. Try x1, x3, x4, x8, or x16 speeds. If this does not work, try a pot adjustment and turn the DVD laser a little counterclockwise to lower resistance of the laser and make it read burned discs.

This fixed my issue , I bought a Verbatim DVD-R burnt it at lowest speed on CDBURNERXP with finalized and compatibility options enabled and it worked first try! Thank you so much !
