### ISSUE TITLE
Exfat Support?

### ISSUE THREAD

**Issue by VisionR1** [CTurt/FreeDVDBoot#314]
Hi, the latest opl 1.2.0 support exfat but when load from disc the FreeDVDBoot and go to mass is empty

**Comment by VisionR1** [comment]
> Hi, the latest opl 1.2.0 support exfat but when load from disc the FreeDVDBoot and go to mass is empty

Finally the usb had the problem

**Comment by heevock** [comment]
Hi, could you describe your problem? was it formatting issue?

**Comment by VisionR1** [comment]
> Hi, could you describe your problem? was it formatting issue?

Yeah, i think, It's been a while since I wrote this, but i think something with usb must set to active, MRB something like that

**Comment by heevock** [comment]
Im trying to launch opl from 64GB usb drive with exFAT. FreeDVDboot loads but ps2 can't read my usb drive. I've tried both MBR and GPT, tried different opl versions. Im really stuck    D:

**Comment by VisionR1** [comment]
> Im trying to launch opl from 64GB usb drive with exFAT. FreeDVDboot loads but ps2 can't read my usb drive. I've tried both MBR and GPT, tried different opl versions. Im really stuck D:

I think this happens because inside in the FreeDVDboot have old wLaunchELF without exFat support, i have mod the original and merge the new wLaunchELF with exFat support to make the usb read it

**Comment by heevock** [comment]
where could I find this new version of FreeDVDboot? I guess I burned the 4 year old version

**Comment by VisionR1** [comment]
> where could I find this new version of FreeDVDboot? I guess I burned the 4 year old version

Not exist i manually chance the old wLaunchELF from inside with new version of wLaunchELF

**Comment by heevock** [comment]
(o _ o  ) Would you explain, how can I do it myself? or send the file maybe

**Comment by VisionR1** [comment]
> (o _ o ) Would you explain, how can I do it myself? or send the file maybe

Sorry for late response i try found the file, burn it with the same instructions (i hope works) and explain for how chance  initial program is in the instructions front page

[All PS2 slims (3.10 + 3.11) - English language.zip](https://github.com/CTurt/FreeDVDBoot/files/14271863/All.PS2.slims.3.10.%2B.3.11.-.English.language.zip)

**Comment by heevock** [comment]
thank you!

**Comment by VisionR1** [comment]
> thank you!

When you test it, write here if it is works, to know and other users

**Comment by heevock** [comment]
> > thank you!
> 
> When you test it, write here if it is works, to know and other users

ok. As soon as I get empty disk for it

**Comment by VisionR1** [comment]
> > > thank you!
> > 
> > 
> > When you test it, write here if it is works, to know and other users
> 
> ok. As soon as I get empty disk for it

Yeah, no problem, no rush

**Comment by VisionR1** [comment]
Here for FreeDVDBoot with new wLaunchELF https://github.com/CTurt/FreeDVDBoot/issues/356
