### ISSUE TITLE
SCPH-70004 (3.10E) the disc could not be read

### ISSUE THREAD

**Issue by Sefohui** [CTurt/FreeDVDBoot#316]
So I'm trying to softmod my ps2 slim. Whatever I do it seems like it doesn't wanna work. It takes a while reading the disc until it says that it couldn't be read. I have tried putting in 3 different dvd films where one of them is burnt on the same sort of dvd-r disc I used for FDVDB (Verbatim DVD-R). I have tried both 4x speed and all the way down to 1x. I have tried the "All PS2 Slims - English language.iso" version and also a hybrid for 3.10 especially. Nothing worked. I have tried unplugging my controller, MC, usb-drive. All seperately and togheter. Doesn't work. I'm just at a loss. I don't know what I'm doing wrong.

**Comment by SIMBAPSX** [comment]
check at the latest post on issues :D
