### ISSUE TITLE
The disc could not be read.

### ISSUE THREAD

**Issue by olivia1246** [CTurt/FreeDVDBoot#338]
I have a PS2 Slim (PAL) (SCPH-70004)
DVD Player 3.10E

DVD Video: Works sometimes? It seems to be random if it wants to read or not. The disc that loaded always though was a DVD Video of a PS2 Game *Formula One 2002*. And one DVD Video gave a Play halted due to malfunction and never worked. (DVD Video shows up always on all discs except for FreeDVDBoot)

PS2 Disc: It doesn't seem to read PS2 Games that well (My games discs do have a lot of visible scratches so it may have trouble reading because of it). 1 out of 6 total games crashed but loaded and worked for a few minutes. 2 out of 6 games didn't load the game (Loading screen errors and black screen). 3 out of 6 games worked fine.

I used this prebuilt
https://github.com/CTurt/FreeDVDBoot/raw/master/PREBUILT%20ISOs/All%20PS2%20Slims%20-%20English%20language.iso

I used a Verbatim DVD-R I burned using CDBurnerXP at 1x speed (1,000≅ KB) but that didn't work and DVD Video didn't show up
I tried copying over the "VIDEO_TS" folder to a another Verbatim DVD-R but that didn't work too and DVD Video also didn't show up (I know it was dumb)

I think it may have a disc drive that is "dying" or it could be because of the computer or/and DVD Drive that I used to burn it. (Amilo Pro V3515)

If there's any suggestions or ideas you could give that could be helpful please tell me. (I only currently have 1 DVD-R disc left. But I do have a DVD+RW Verbatim disc although the computer I use doesn't allow me to rewrite it)

**Comment by ElekN** [comment]
Does your disc support burning at 1x speed? I had the same problem when I burned at 1x speed and then I noticed that lowest my disc supports is 4x, so I burned it in 4x and it worked. I'm not sure how you can check it on CDBurnerXP, but if you download ImgBurn you have a section where it displays your disc information. There you can find supported burning speeds. Just select the lowest one and it should hopefully work.

![Screenshot 2023-06-18 004054](https://github.com/CTurt/FreeDVDBoot/assets/72307054/cca660ef-7106-46ca-912f-cfcff6de9a1f)

**Comment by ghost** [comment]
The writing speed is defined in the burner's firmware, even if you can go under it's not a good idea . Olivia12456, just burn the normal ISO to a DVD-R with IMGBurn at 4x . If that doesn't work you have laser issues, just gen a FMCB memory card and use OPL .

**Comment by olivia1246** [comment]
Thank you for the suggestions however I think the laser broke because it isn't reading any discs anymore.
