### ISSUE TITLE
Can you run ISO file with FreeDVDBoot ?

### ISSUE THREAD

**Issue by Windows98SE-dev** [CTurt/FreeDVDBoot#351]
Hello,
I recently burned a disc with FreeDVDBoot but I have a question,

Can you play ISO files stored on a USB Flash Drive ?

**Comment by akarapatakis** [comment]
If I am not mistaken, FDVDBoot launches uLaunchELF where you can install FMCB to your memory card and by there, you can install OPL and launch games off usb from there (but it is not recommended, if we take into consideration the speed rate of PS2's USB ports, you may experience issues)

**Comment by Windows98SE-dev** [comment]
Yeah this what I did, I forgot to close the issue

**Comment by Windows98SE-dev** [comment]
Yeah this what I did, I forgot to close the issue. Anyways, Thanks
