### ISSUE TITLE
Start running usb games 

### ISSUE THREAD

**Issue by ExactGosling721** [CTurt/FreeDVDBoot#38]
my games go not show up on opl, so it might be where i got the games from or how i put it on the usb. Does anyone know where i found find iso games and also how to put them on the usb so that i can see them when running opl , Thank You!

**Comment by J013k** [comment]
If you will give more info it will easier to help you...

What OPL version you try?
Does in wLaunchELF (mass:) your USB device is visible?
Where did you put ISO images (picture will be nice)?
Did you enable USB Device in settings (Off - Manual - Auto)? By default `Off` is set.

Additionally topic related with OPL can be found elsewhere,
not especially at FreeDVDBoot issues.

**Comment by ExactGosling721** [comment]
sorry about that, i was following the steps to the solution of a past open issue on this forum, i entered ulauch through free dvd boot

everything loads up but the games won’t show even though they are in the dvd folders and everything, when i get to opl to press circle nothing comes up and i have set the usb to manual as well. i’ve sent pictures below but i don’t know if you can see them 


![195D863C-3EE3-4AD2-80A1-5DAC8DDC9B38](https://user-images.githubusercontent.com/67714236/86388394-59545900-bc5a-11ea-856b-f6da5aa07f8d.jpeg)


![35254563-5F4C-4DD3-956D-E1D252D31F53](https://user-images.githubusercontent.com/67714236/86388362-4f325a80-bc5a-11ea-815a-ef46db0e249e.jpeg)
![D20B6313-F16F-43EB-B79E-C5933E99552E](https://user-images.githubusercontent.com/67714236/86388378-53f70e80-bc5a-11ea-9788-2db63057909e.jpeg)
![56684373-E407-47C2-ABA5-8AE3C24FA70F](https://user-images.githubusercontent.com/67714236/86388381-55283b80-bc5a-11ea-8bc9-8787fedf27b9.jpeg)
![6B97B12C-206D-49A7-BB0C-65855788D89C](https://user-images.githubusercontent.com/67714236/86388386-56f1ff00-bc5a-11ea-883d-2d7b69e90489.jpeg)

**Comment by J013k** [comment]
Looks good.
ISOs larger than 700 MiB are in `DVD` folder (~2 GiB for Def & ~3 GiB Mortal).
You are manually enabling USB device (additionally you can try auto).
The only problem I see is that OPL should create additional folders at startup of device:
- ART
- CD
- CFG
- CHT
- DVD
- THM

Can you try this (1436) version of an OPL:
https://www.psx-place.com/threads/open-ps2-loader-v0-9-3.13415/page-47#post-225201.
Or another test (1514) build:
https://www.psx-place.com/threads/open-ps2-loader-v0-9-3.13415/page-50#post-248856.

Additionally try to pullout USB device, wait few sec (~30 s) and plug it again.

**Comment by ExactGosling721** [comment]
I tried both links and they both showed up but still didn’t pull up the games, i may be wrong but i believe it’s the file type, on youtube tutorials their file types say “ disc image file” but mine says “iso image”, also the opl didn’t create all the other extra files only the ones u created which were the “dvd” and “cd”

**Comment by J013k** [comment]
You have `ISO image` because maybe you are using different app\program to support\write these ISOs.

How many others thumb drive(s) you have?
Can you try another one at least with one game in DVD folder?

Additionally You can try to rename ISOs:
`SLUS_206.39.Def Jam - Vendetta`
`SLUS_210.87.Mortal Kombat - Shaolin Monks`
both with `.Iso` file extension.

**Comment by ExactGosling721** [comment]
it didn’t work, it might be on my end  as in where i got the game from, do you know a site where i can get iso so i can start the download process over? 

first i download iso then extract the iso file and then put that extracted file into the usb is that correct?

**Comment by ExactGosling721** [comment]
and that is the only thumb drive i currently own

**Comment by VersatileNinja** [comment]
Highly recommend you watch the ps2 opl usb tutorial at project phoenix media on youtube.

**Comment by ExactGosling721** [comment]
i’m thankful for both of you trying to help :). yes i’ve seen majority of his videos and nothing still works, i might just try a different game and see if it works but it’ll be disappointing if this is just happening to me alone  cuz why lol

**Comment by VersatileNinja** [comment]
Use opl manager v21.6 to fix your game file names and then try again.

**Comment by J013k** [comment]
For me it is compatibility issue with thumb drive.

Even without any game or with incorrect game image OPL **should create additional folders** (ART, CD...).
At least OPL 1436, 1514 does that.

**Comment by ExactGosling721** [comment]
do you have a video covering how to use opl manager?

**Comment by VersatileNinja** [comment]
On Project Phoenix Media YouTube, go to Ps2 modding Playlist and look up few weeks back beginner's guide to Ps2 usb games.  OPL Manager is covered in there.

**Comment by ExactGosling721** [comment]
ok i got it to open the games list and it’s working now, all the games i’ve downloaded works except for kingdom hearts 2, and it says it’s “fragmented”

**Comment by HowlingWolfHWC** [comment]
You need to defrag it.

**Comment by CTurt** [comment]
OPL issues has nothing to do with this project.
