### ISSUE TITLE
3.02U ps2 Will freedvdboot run?

### ISSUE THREAD

**Issue by braxton092408** [CTurt/FreeDVDBoot#4]
Will freedvdboot run on my 3.02U dvd player firmware ps2? I would also like to test it on my ps2 but i have no idea how to do this. Is there any video tutorials currently out?

**Comment by parkerlreed** [comment]
Other versions will need to be worked on specifically. So currently the answer is no, but there's a good chance it'll work in the near future.

**Comment by CTurt** [comment]
Correct
