### ISSUE TITLE
Black screen in Compatible version

### ISSUE THREAD

**Issue by jvhellraiser** [CTurt/FreeDVDBoot#41]
Ps2 Fat 90000, dvd player 3:10U
i burn the ISO file containing Ulauncher to a DVD -
try to boot into my PS2 but the screen stays in a black screen.
please help any ideas on to why this happens?

![106541888_716385002545972_2805663799624431332_o](https://user-images.githubusercontent.com/16488761/86411242-6a1cc300-bc8a-11ea-920e-974cf4b0968c.jpg)

**Comment by zacchi4k** [comment]
Did you change the language to English?

**Comment by jvhellraiser** [comment]
it is fix now thanks....

**Comment by VersatileNinja** [comment]
> it is fix now thanks....

How you fix?

**Comment by zacchi4k** [comment]
If it's fixed you can close the issue
