### ISSUE TITLE
3.10 ISO not working while hybrid does work

### ISSUE THREAD

**Issue by ajimenezc** [CTurt/FreeDVDBoot#48]
PS2 Slim with DVD 3.10E

First tried ISO 3.10 only and it won't be read.
Then tried hybrid, using same DVD brand, same hardware, same software, same everything and loaded instantly.

Can't give more info but hope it helps. It worked with hybrid ISO so I am happy, thanks for your work.

**Comment by CTurt** [comment]
Thanks for the datapoint!
