### ISSUE TITLE
Any chance of 2.12U support soon?

### ISSUE THREAD

**Issue by ltdimwit** [CTurt/FreeDVDBoot#49]
I'd like to know if its worth waiting for before I just go the freeHDboot route instead.

**Comment by voltagex** [comment]
Duplicate of #19

**Comment by ltdimwit** [comment]
He isn't asking the same question I am.

**Comment by VersatileNinja** [comment]
Go FreeHDBoot now and go 2.12U in future whenever CTurt gets around to it, he isn't making any promises.

**Comment by ltdimwit** [comment]
Thanks.

**Comment by parkerlreed** [comment]
2.12U is out
