### ISSUE TITLE
Unable to read disc

### ISSUE THREAD

**Issue by LPCC12** [CTurt/FreeDVDBoot#50]
I get unable to read disc every time, it enters the dvd but gets black screen with 'unable to read disc.' most likely my laser... I´ve tried DVD-R and +R and same thing... -R seens to stay on black screen more time before showing the message... Any tips? Maybe a costum disc setup with a lighter file so it gets to read less things and boot?

**Comment by VersatileNinja** [comment]
Not sure what dvd player version you got, did you try the 3.10 or 3.11 specific version as well as the hybrid disc version for your ps2?

**Comment by LPCC12** [comment]
3.10E Tryed burning with Windows and ImgBurn / High burn speed and low. Veryfing after burn.

**Comment by chichonaizer** [comment]
Hola!
He descargado 3.11 only-all regions-English lang.iso. He quemado con ultraiso a10X pero marca a 8X en un DVD-R.
He limpiado y jugado con juegos originales y funciona pero el DVD quemado no.
Podrías ayudarme?
Por cierto, mi consola es SCPH-77004 v15  Slim Pstwo 1.40 2.00 2.00 3.11E

**Comment by marko-radojcic** [comment]
My console is ROM version 30004. It refuses to read any non-original disc. Maybe it is for the best, but if anyone has an answer please ping me. Btw, Does it have to be burned on DVD or CD is ok ?

**Comment by chichonaizer** [comment]
> ¡Hola!
> Descargado 3.11 solo-todas las regiones-inglés lang.iso. Quemó con ultraiso a10X pero marca a 8X en un DVD-R.
> Él limpiado y jugado con juegos originales y funciona pero el DVD quemado no.
> Podrías ayudarme?
> Por cierto, mi consola es SCPH-77004 v15 Slim Pstwo 1.40 2.00 2.00 3.11E

Hola de nuevo!
He comprado de la marca "Verbatim" y ha funcionado aunque la play le cuesta leer.
ahora me ha surgido un problema y es que el disco duro externo USB de 1TB que preparado basandome en tus tutoriales, no me funciona pero sin embargo un USB de 8Gigas si.
Sabes a que es debido?

**Comment by CTurt** [comment]
Have you tried playing a regular DVD movie? This can sometimes recalibrate the laser.

**Comment by marko-radojcic** [comment]
My console still plays the one original game I have perfectly. But movie DVDs or non-original games no. It also makes a clacking sound when I insert any other DVD except from the game I have. I support legal software, but original PS2 games are almost impossible to find in Serbia.
