### ISSUE TITLE
Could you save games loaded via DVD to a USB storage?

### ISSUE THREAD

**Issue by Fran7Ribeiro** [CTurt/FreeDVDBoot#51]
Could you create a virtual memory card with a USB device to save the game files? I plan on loading the games via the dvd/cd reader. I know that with some homebrews you could do that but only with games loaded via USB too.

**Comment by VersatileNinja** [comment]
Using OPL and VMC support yes you can. See the VMC tutorials at ps2-home.com

**Comment by CTurt** [comment]
Not related to FreeDVDBoot.
