### ISSUE TITLE
> but for real i have an aplication that is generating radom Freedvdboot isos this app that i gave you was just an joke

### ISSUE THREAD

**Issue by helpme20** [CTurt/FreeDVDBoot#53]
> but for real i have an aplication that is generating radom Freedvdboot isos this app that i gave you was just an joke
> 
> i spend a lot of time to program the real one
Why would anyone believe at you?Also,your grammar is horrible.

_Originally posted by @Rodrigo1781Violencia in https://github.com/CTurt/FreeDVDBoot/issues/47#issuecomment-653770604_

**Comment by lvlhead** [comment]
You're not helping yourself. If you have an application for that, cool. There's nothing in your profile to suggest it exists, you can't tell us how it operates or what programs it uses, and you become defensive whenever someone calls you out.

Please just give it up.
