### ISSUE TITLE
Are there any scripts for generating pre-built ISOs?

### ISSUE THREAD

**Issue by requeijaum** [CTurt/FreeDVDBoot#8]
No need for commenting on this. Already on the [title](#Are_there_any_scripts_for_generating_pre-built_ISOs).

**Comment by CTurt** [comment]
It's a single command, as explained in the README.

    genisoimage -udf -o output.iso Filesystem/version/

**Comment by requeijaum** [comment]
Got it! 
Point the filesystem folder - with my target DVD Player version - to genisoimage!

**Comment by CTurt** [comment]
But as an aside, I would like to make better build scripts for inserting payloads automatically into VIDEO_TS.IFO. Currently the code is a bit of a mess.
